### ISSUE TITLE
Not working for Pie

### ISSUE THREAD

**Issue by m-usmankhan** [stavangr/SplitScreenLauncher#1]
On Android 9.0 / Pie, it attempts to open apps in split screen but it fails. I have tried on several devices. Can u fix it soon? I need it.

**Comment by paprikanotfound** [comment]
It works fine on Android 9.0 here. Are you sure the apps support split-screen mode?

**Comment by m-usmankhan** [comment]
Well.. it's like.. I can manually open both apps to Split screen view, using the Recent apps button. 
I believe I have added the "split screen support" in my apps, as per https://stackoverflow.com/q/39451988/1397821 
My targetSdkVersion is 29 and I have set resizeableActivity="true" in <application> tag

3 things happening here
1.   When I launch my apps, using SplitScreenLauncher, it attempts to open them in split screen but then it immediately closes the 2nd app (i tried swapping the apps).  It shows no error/message.
2. I try Youtube and Instagram. It clearly says "Your app doesnt support split screen" for Instagram.
3. I just tried Youtube and Google Maps, it works.

Another finding:
- When I use Youtube as first and MyApp as second app, then it works. And if I use MyApp as first and Youtube as second app, then it doesnt work (acts like step 1). This is true for both of my apps, I tried one by one.
.
So what would you suggest me here?

(btw thanks for all ur code and support)

**Comment by paprikanotfound** [comment]
Have you tried to enable the accessibility service? Is there any way I can reproduce this on my device?

**Comment by m-usmankhan** [comment]
I found the problem. It was in my Apps, both apps unfortunately. After Splash screen, I was doing startActivity() after finish(). `finish()` was closing all activities before i could start new, so split screen was going away. Now I finish() after startActivity(), and it works. 
Sorry to bother you !
