### ISSUE TITLE
only opens one app

### ISSUE THREAD

**Issue by Offbeatmammal** [stavangr/SplitScreenLauncher#3]
had a play with this today on a Pixel3 / Android 11 as it seems to be exactly what I want... but
it appeared to correctly open Waze and then Torque Plus apps, and went into split screen mode but then Waze disappeared, and as soon as I tried to interact with Torque Plus (or rotate the phone to landscape) Torque Plus went back to full screen.

**Comment by paprikanotfound** [comment]
Some apps don't work well with split-screen, can you confirm that you can enable split-screen manually with these two apps?
